---
- name: Test getting weather information
  hosts: localhost

  tasks:
    - name: REST GET CMDB Data in ServiceNow
      uri:
        url: "https://dev85503.service-now.com/api/now/table/cmdb_ci_server"
        method: GET
        user: bforrest
        password: EBf2009$#
        return_content: yes
        body_format: json
      ignore_errors: yes
      register: get_cmdb_data

    - debug:
        var: get_cmdb_data 